//go:build ignore

// tablegen generates lookup tables.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"

	"github.com/clfs/simple/core"
)

var output = flag.String("output", "tables.go", "file name to write")

const header = `
package movegen

import "github.com/clfs/simple/core"
`

func main() {
	log.SetFlags(0)
	log.SetPrefix("tablegen: ")
	flag.Parse()
	if flag.NArg() != 0 {
		log.Fatal("usage: tablegen [--output filename]")
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by go run tablegen.go -output %s; DO NOT EDIT.\n\n", *output)
	fmt.Fprint(&b, header)

	writeTable(&b, "whitePawnPushes", whitePawnPushes())
	writeTable(&b, "blackPawnPushes", blackPawnPushes())
	writeTable(&b, "whitePawnAttacks", whitePawnAttacks())
	writeTable(&b, "blackPawnAttacks", blackPawnAttacks())

	source, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal("source format error:", err)
	}
	fd, err := os.Create(*output)
	if err != nil {
		log.Fatal(err)
	}
	if _, err := fd.Write(source); err != nil {
		log.Fatal(err)
	}
}

// writeTable writes table to w as a Go array.
func writeTable(w io.Writer, name string, table []core.Bitboard) {
	fmt.Fprintf(w, "var %s = [%d]core.Bitboard{\n", name, len(table))
	for i := range table {
		fmt.Fprintf(w, "%d,\n", table[i])
	}
	fmt.Fprint(w, "}\n\n")
}

func whitePawnPushes() []core.Bitboard {
	var table [64]core.Bitboard
	for s := core.A2; s <= core.H7; s++ {
		table[s].Set(s.Above())
		if s.Rank() == core.Rank2 {
			table[s].Set(s.Above().Above())
		}
	}
	return table[:]
}

func blackPawnPushes() []core.Bitboard {
	var table [64]core.Bitboard
	for s := core.A2; s <= core.H7; s++ {
		table[s].Set(s.Below())
		if s.Rank() == core.Rank7 {
			table[s].Set(s.Below().Below())
		}
	}
	return table[:]
}

func whitePawnAttacks() []core.Bitboard {
	var table [64]core.Bitboard
	for s := core.A2; s <= core.H7; s++ {
		if s.File() != core.FileA {
			table[s].Set(s.Above().Left())
		}
		if s.File() != core.FileH {
			table[s].Set(s.Above().Right())
		}
	}
	return table[:]
}

func blackPawnAttacks() []core.Bitboard {
	var table [64]core.Bitboard
	for s := core.A2; s <= core.H7; s++ {
		if s.File() != core.FileA {
			table[s].Set(s.Below().Left())
		}
		if s.File() != core.FileH {
			table[s].Set(s.Below().Right())
		}
	}
	return table[:]
}
